tuple_buah = ('Pisang', 'Nanas', 'Melon', 'Durian', 'nangka', 'strawberry', 'mangga')

print(tuple_buah[0:1])
print(tuple_buah[0:2])
print(tuple_buah[1:3])
print(tuple_buah[0:-1])
print(tuple_buah[-1:-3])
print(tuple_buah[-1:3])
print(tuple_buah[-3:-1])
print(tuple_buah[-8:-1])
